#!/usr/bin/env bash
[ $(hostname) == "zen" ] || exit 0
root=$(df -h | ned --color=never -Lg 1 '\s(\d+)G\s+\d+%\s/$')
big="0" # $(df -h | ned --color=never -Lg 1 '\s(\d+)G\s+\d+%\s/big$')
msg="家　/　${root} ギガ　/big　${big} ギガ"
if [ "$root" -lt 25 ] || [ "$big" -lt 100 ]; then
	echo "<span foreground='#ffffff' background='#ff0000'><b> $msg! </b></span>"
else
	echo $msg
fi
