#!/usr/bin/env bash
if git branch -a | grep -q 'origin/main'; then
    m="main"
else
    m="master"
fi
git log --pretty=format:"%Cgreen%h %C(yellow)[%cd]%Cred%d %Creset%s%Cblue [%cn]" --decorate --date=local --no-merges HEAD --not "origin/$m~1"
